export const BLOGConstant = {
  UPDATE_BLOG_REQUEST: "UPDATE_BLOG_REQUEST",
  UPDATE_BLOG_SUCCESS: "UPDATE_BLOG_SUCCESS",
  UPDATE_BLOG_FAILURE: "UPDATE_BLOG_FAILURE",

  BLOG_CREATE_SUCCESS: "BLOG_CREATE_SUCCESS",
  BLOG_CREATE_FAILURE: "BLOG_CREATE_FAILURE",
  BLOG_CREATE_REQUEST: "BLOG_CREATE_REQUEST",
};
